import { notFound } from "next/navigation";
import { InnerPage } from "@/components/inner-page";

const services: Record<string, { name: string; problem: string; capabilities: string[]; outcomes: string[]; deliverables: string[] }> = {
  "digital-marketing": { name: "Digital Marketing", problem: "Your channels should work from one commercial plan, not as separate publishing tasks.", capabilities: ["Digital strategy", "Content and campaign planning", "Landing-page journeys", "Conversion measurement"], outcomes: ["A clearer message hierarchy", "A sharper demand-generation engine", "Better lead quality and conversion"], deliverables: ["Channel strategy", "Campaign architecture", "Content calendar", "Measurement framework"] },
  "performance-marketing": { name: "Performance Marketing", problem: "Paid acquisition needs a clear path from attention to qualified enquiry.", capabilities: ["Google Ads", "Meta Ads", "Audience and creative testing", "Conversion tracking"], outcomes: ["Higher efficiency per acquisition", "Fewer wasted clicks", "Faster learning cycles"], deliverables: ["Ad account structure", "Creative testing plan", "Tracking setup", "Weekly optimization cadence"] },
  seo: { name: "SEO", problem: "Search visibility is only useful when it brings the right people to useful pages.", capabilities: ["Technical SEO", "Local SEO", "Content strategy", "Search-led landing pages"], outcomes: ["Improved discovery", "More qualified organic traffic", "A stronger digital foundation"], deliverables: ["Technical SEO review", "Keyword and content plan", "On-page improvements", "Reporting dashboard"] },
  "social-media-marketing": { name: "Social Media Marketing", problem: "Social content should support trust and demand, not exist apart from the business.", capabilities: ["Content systems", "Creative direction", "Community touchpoints", "Campaign support"], outcomes: ["Stronger brand recall", "More useful audience engagement", "Better message-market fit"], deliverables: ["Content pillars", "Creative direction", "Posting system", "Engagement workflow"] },
  "web-development": { name: "Web Development", problem: "A website should make the next step obvious and give your marketing somewhere useful to land.", capabilities: ["Marketing websites", "Landing pages", "Performance foundations", "Integrations"], outcomes: ["Clearer conversion flow", "Better trust at first impression", "A stronger sales enablement layer"], deliverables: ["UX and wireframe direction", "Build and QA", "Performance optimization", "Integrations and handoff"] },
  "e-commerce": { name: "E-commerce", problem: "Product discovery, purchase and retention should feel like one connected experience.", capabilities: ["Storefronts", "Product content", "Conversion optimisation", "Retention workflows"], outcomes: ["Stronger purchase confidence", "Lower drop-off at key moments", "Better recurring value"], deliverables: ["Store UX review", "Product funnel planning", "Retention flows", "Checkout experience refinement"] },
  branding: { name: "Branding", problem: "A clear brand helps the right customers understand why your business matters.", capabilities: ["Positioning", "Visual identity", "Campaign systems", "Brand guidelines"], outcomes: ["Sharper positioning", "Better trust and recall", "More consistent communication"], deliverables: ["Brand narrative", "Visual direction", "Campaign toolkit", "Usage guidelines"] },
  "lead-generation": { name: "Lead Generation", problem: "Interest should become a trackable enquiry that your team can act on quickly.", capabilities: ["Funnel design", "Lead forms", "Qualification", "CRM handoff"], outcomes: ["Better lead quality", "Faster follow-up", "Stronger qualification logic"], deliverables: ["Funnel mapping", "Lead capture system", "Qualification rules", "Sales handoff workflow"] },
  "crm-automation": { name: "CRM and Automation", problem: "Manual follow-up creates gaps between a lead showing interest and a sales conversation.", capabilities: ["CRM setup", "WhatsApp and email workflows", "Lead routing", "Reporting"], outcomes: ["Fewer dropped leads", "Faster team response", "More visible pipeline health"], deliverables: ["CRM configuration", "Automation flows", "Lead routing", "Reporting layer"] },
  "ai-solutions": { name: "AI Solutions", problem: "AI should remove repetitive work while staying useful, reviewable and grounded in your process.", capabilities: ["Workflow automation", "AI assistants", "Internal tools", "Process mapping"], outcomes: ["Less repetitive work", "Better operational consistency", "More time for revenue-driving tasks"], deliverables: ["Process mapping", "Prompt and workflow design", "Tool setup", "Review and governance model"] },
};

export function generateStaticParams() { return Object.keys(services).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const service = services[slug]; return service ? { title: `${service.name} | TheDark8 Tech`, description: service.problem, alternates: { canonical: `/services/${slug}` } } : {}; }
export default async function ServicePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const service = services[slug]; if (!service) notFound(); return <InnerPage eyebrow={`Service / ${service.name}`} title={<>Make the next move <em>more useful.</em></>} intro={service.problem}><section className="section shell service-landing"><div className="service-hero"><div className="service-hero-copy"><p className="eyebrow">Commercial system</p><h2>Turn {service.name.toLowerCase()} into a measurable growth lever.</h2></div><div className="service-metrics">{service.outcomes.slice(0,3).map((outcome, index) => <div className="service-metric" key={outcome}><span>0{index + 1}</span><strong>{outcome}</strong></div>)}<div className="service-metric service-metric-cta"><span>Delivery</span><strong>{service.deliverables.length} core workstreams</strong></div></div></div><div className="detail-shell"><div className="detail-panel"><p className="eyebrow">What we build around</p><div className="industry-detail">{service.capabilities.map((capability, index) => <div key={capability}><span>0{index + 1}</span><strong>{capability}</strong></div>)}</div></div><div className="detail-panel accent-panel"><p className="eyebrow">What changes</p><ul className="detail-list">{service.outcomes.map((outcome) => <li key={outcome}>{outcome}</li>)}</ul></div></div><div className="detail-grid"><div className="detail-card"><p className="eyebrow">Delivery shape</p><ul className="detail-list">{service.deliverables.map((deliverable) => <li key={deliverable}>{deliverable}</li>)}</ul></div><div className="detail-card"><p className="eyebrow">Operating model</p><p>We scope the work based on business goals, customer behaviour and the system already in place. The result is a solution that fits your market, your team and the decisions you need to make next.</p></div></div></section></InnerPage>; }
