import { notFound } from "next/navigation";
import { InnerPage } from "@/components/inner-page";

const content: Record<string, { name: string; focus: string; points: string[]; bottlenecks: string[]; levers: string[] }> = {
  manufacturing: { name: "Manufacturing", focus: "Build a B2B acquisition system around technical products, RFQs and distributor relationships.", points: ["Technical SEO and product pages", "Google Search and LinkedIn acquisition", "Distributor and international enquiries", "RFQ forms, CRM and email follow-up", "Analytics that connect enquiries to sales"], bottlenecks: ["Complex product information spread across departments", "Weak differentiation in search and discovery", "Manual quoting and inquiry handling"], levers: ["Product-led content strategy", "Lead qualification and routing", "Sales-enablement tooling"] },
  healthcare: { name: "Healthcare", focus: "Create a clear local discovery and patient acquisition journey built around trust and useful information.", points: ["Local search visibility", "Service and practitioner pages", "Lead capture and enquiry routing", "Content that answers patient questions", "Privacy-aware measurement"], bottlenecks: ["Low trust in digital experience", "Inconsistent conversion paths across services", "Long delays between enquiry and response"], levers: ["Local SEO and trust-building pages", "Intake flow simplification", "Patient journey automation"] },
  education: { name: "Education", focus: "Help prospective students move from discovery to a confident admission enquiry.", points: ["Course and programme landing pages", "Search and paid admission campaigns", "Lead qualification and counsellor routing", "WhatsApp and email follow-up", "Enquiry-to-admission reporting"], bottlenecks: ["Prospective students do not see a clear next step", "Counsellor follow-up is inconsistent", "Admissions data is fragmented"], levers: ["Programme-specific landing pages", "Campaign and funnel alignment", "Structured enquiry workflows"] },
  retail: { name: "Retail", focus: "Connect e-commerce, local acquisition and retention into a more useful customer journey.", points: ["E-commerce experience and CRO", "Local discovery and paid acquisition", "Product content and SEO", "Customer retention workflows", "Analytics across store and digital touchpoints"], bottlenecks: ["Traffic is not matching intent", "Product pages are not converting consistently", "Post-purchase retention is weak"], levers: ["E-commerce and local funnel alignment", "Retention loops and customer data", "Offer strategy and CRO"] },
  hospitality: { name: "Hospitality", focus: "Build a digital path from local discovery to direct enquiry and booking.", points: ["Local search and destination content", "Direct booking experience", "Paid acquisition and remarketing", "WhatsApp enquiry workflows", "Measurement across discovery and booking"], bottlenecks: ["Discovery content is not converting to direct action", "Booking flow is fragmented", "Guest enquiry follow-up is uneven"], levers: ["Local acquisition strategy", "Trust-building content", "Booking and inquiry automation"] },
};

export function generateStaticParams() { return Object.keys(content).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const industry = content[slug]; return industry ? { title: `${industry.name} Growth Systems | TheDark8 Tech`, description: industry.focus, alternates: { canonical: `/industries/${slug}` } } : {}; }
export default async function IndustryPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const industry = content[slug]; if (!industry) notFound(); return <InnerPage eyebrow={`Industry / ${industry.name}`} title={<>Digital growth for <em>{industry.name.toLowerCase()}.</em></>} intro={industry.focus}><section className="section shell industry-landing"><div className="industry-signal"><div><p className="eyebrow">Market lens</p><h2>{industry.name} <em>growth system.</em></h2></div><div className="industry-signal-stat"><strong>{industry.points.length}</strong><span>priority levers</span></div></div><div className="detail-shell"><div className="detail-panel"><p className="eyebrow">Recommended focus</p><div className="industry-detail">{industry.points.map((point, index) => <div key={point}><span>0{index + 1}</span><strong>{point}</strong></div>)}</div></div><div className="detail-panel accent-panel"><p className="eyebrow">Common bottlenecks</p><ul className="detail-list">{industry.bottlenecks.map((bottleneck) => <li key={bottleneck}>{bottleneck}</li>)}</ul></div></div><div className="detail-grid"><div className="detail-card"><p className="eyebrow">System levers</p><ul className="detail-list">{industry.levers.map((lever) => <li key={lever}>{lever}</li>)}</ul></div><div className="detail-card"><p className="eyebrow">What good looks like</p><p>Growth becomes easier when acquisition, conversion and follow-up are designed around the decision-making process of real customers in this market. That means clearer messaging, better handoff and more useful measurement.</p></div></div></section></InnerPage>; }
